# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/data0/DarknessSpeckleSuppression

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/data0/DarknessSpeckleSuppression

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/data0/DarknessSpeckleSuppression/CMakeFiles /mnt/data0/DarknessSpeckleSuppression/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/data0/DarknessSpeckleSuppression/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PacketMasterSim

# Build rule for target.
PacketMasterSim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PacketMasterSim
.PHONY : PacketMasterSim

# fast build rule for target.
PacketMasterSim/fast:
	$(MAKE) -f CMakeFiles/PacketMasterSim.dir/build.make CMakeFiles/PacketMasterSim.dir/build
.PHONY : PacketMasterSim/fast

#=============================================================================
# Target rules for targets named SpeckleDestruction

# Build rule for target.
SpeckleDestruction: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SpeckleDestruction
.PHONY : SpeckleDestruction

# fast build rule for target.
SpeckleDestruction/fast:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/build
.PHONY : SpeckleDestruction/fast

sim/PacketMasterSim.o: sim/PacketMasterSim.cpp.o
.PHONY : sim/PacketMasterSim.o

# target to build an object file
sim/PacketMasterSim.cpp.o:
	$(MAKE) -f CMakeFiles/PacketMasterSim.dir/build.make CMakeFiles/PacketMasterSim.dir/sim/PacketMasterSim.cpp.o
.PHONY : sim/PacketMasterSim.cpp.o

sim/PacketMasterSim.i: sim/PacketMasterSim.cpp.i
.PHONY : sim/PacketMasterSim.i

# target to preprocess a source file
sim/PacketMasterSim.cpp.i:
	$(MAKE) -f CMakeFiles/PacketMasterSim.dir/build.make CMakeFiles/PacketMasterSim.dir/sim/PacketMasterSim.cpp.i
.PHONY : sim/PacketMasterSim.cpp.i

sim/PacketMasterSim.s: sim/PacketMasterSim.cpp.s
.PHONY : sim/PacketMasterSim.s

# target to generate assembly for a file
sim/PacketMasterSim.cpp.s:
	$(MAKE) -f CMakeFiles/PacketMasterSim.dir/build.make CMakeFiles/PacketMasterSim.dir/sim/PacketMasterSim.cpp.s
.PHONY : sim/PacketMasterSim.cpp.s

src/ImageGrabber.o: src/ImageGrabber.cpp.o
.PHONY : src/ImageGrabber.o

# target to build an object file
src/ImageGrabber.cpp.o:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/ImageGrabber.cpp.o
.PHONY : src/ImageGrabber.cpp.o

src/ImageGrabber.i: src/ImageGrabber.cpp.i
.PHONY : src/ImageGrabber.i

# target to preprocess a source file
src/ImageGrabber.cpp.i:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/ImageGrabber.cpp.i
.PHONY : src/ImageGrabber.cpp.i

src/ImageGrabber.s: src/ImageGrabber.cpp.s
.PHONY : src/ImageGrabber.s

# target to generate assembly for a file
src/ImageGrabber.cpp.s:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/ImageGrabber.cpp.s
.PHONY : src/ImageGrabber.cpp.s

src/P3KCom.o: src/P3KCom.cpp.o
.PHONY : src/P3KCom.o

# target to build an object file
src/P3KCom.cpp.o:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/P3KCom.cpp.o
.PHONY : src/P3KCom.cpp.o

src/P3KCom.i: src/P3KCom.cpp.i
.PHONY : src/P3KCom.i

# target to preprocess a source file
src/P3KCom.cpp.i:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/P3KCom.cpp.i
.PHONY : src/P3KCom.cpp.i

src/P3KCom.s: src/P3KCom.cpp.s
.PHONY : src/P3KCom.s

# target to generate assembly for a file
src/P3KCom.cpp.s:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/P3KCom.cpp.s
.PHONY : src/P3KCom.cpp.s

src/Speckle.o: src/Speckle.cpp.o
.PHONY : src/Speckle.o

# target to build an object file
src/Speckle.cpp.o:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/Speckle.cpp.o
.PHONY : src/Speckle.cpp.o

src/Speckle.i: src/Speckle.cpp.i
.PHONY : src/Speckle.i

# target to preprocess a source file
src/Speckle.cpp.i:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/Speckle.cpp.i
.PHONY : src/Speckle.cpp.i

src/Speckle.s: src/Speckle.cpp.s
.PHONY : src/Speckle.s

# target to generate assembly for a file
src/Speckle.cpp.s:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/Speckle.cpp.s
.PHONY : src/Speckle.cpp.s

src/SpeckleDestruction.o: src/SpeckleDestruction.cpp.o
.PHONY : src/SpeckleDestruction.o

# target to build an object file
src/SpeckleDestruction.cpp.o:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/SpeckleDestruction.cpp.o
.PHONY : src/SpeckleDestruction.cpp.o

src/SpeckleDestruction.i: src/SpeckleDestruction.cpp.i
.PHONY : src/SpeckleDestruction.i

# target to preprocess a source file
src/SpeckleDestruction.cpp.i:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/SpeckleDestruction.cpp.i
.PHONY : src/SpeckleDestruction.cpp.i

src/SpeckleDestruction.s: src/SpeckleDestruction.cpp.s
.PHONY : src/SpeckleDestruction.s

# target to generate assembly for a file
src/SpeckleDestruction.cpp.s:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/SpeckleDestruction.cpp.s
.PHONY : src/SpeckleDestruction.cpp.s

src/SpeckleNuller.o: src/SpeckleNuller.cpp.o
.PHONY : src/SpeckleNuller.o

# target to build an object file
src/SpeckleNuller.cpp.o:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/SpeckleNuller.cpp.o
.PHONY : src/SpeckleNuller.cpp.o

src/SpeckleNuller.i: src/SpeckleNuller.cpp.i
.PHONY : src/SpeckleNuller.i

# target to preprocess a source file
src/SpeckleNuller.cpp.i:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/SpeckleNuller.cpp.i
.PHONY : src/SpeckleNuller.cpp.i

src/SpeckleNuller.s: src/SpeckleNuller.cpp.s
.PHONY : src/SpeckleNuller.s

# target to generate assembly for a file
src/SpeckleNuller.cpp.s:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/SpeckleNuller.cpp.s
.PHONY : src/SpeckleNuller.cpp.s

src/dmTools.o: src/dmTools.cpp.o
.PHONY : src/dmTools.o

# target to build an object file
src/dmTools.cpp.o:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/dmTools.cpp.o
.PHONY : src/dmTools.cpp.o

src/dmTools.i: src/dmTools.cpp.i
.PHONY : src/dmTools.i

# target to preprocess a source file
src/dmTools.cpp.i:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/dmTools.cpp.i
.PHONY : src/dmTools.cpp.i

src/dmTools.s: src/dmTools.cpp.s
.PHONY : src/dmTools.s

# target to generate assembly for a file
src/dmTools.cpp.s:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/dmTools.cpp.s
.PHONY : src/dmTools.cpp.s

src/simInterfaceTools.o: src/simInterfaceTools.cpp.o
.PHONY : src/simInterfaceTools.o

# target to build an object file
src/simInterfaceTools.cpp.o:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/simInterfaceTools.cpp.o
.PHONY : src/simInterfaceTools.cpp.o

src/simInterfaceTools.i: src/simInterfaceTools.cpp.i
.PHONY : src/simInterfaceTools.i

# target to preprocess a source file
src/simInterfaceTools.cpp.i:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/simInterfaceTools.cpp.i
.PHONY : src/simInterfaceTools.cpp.i

src/simInterfaceTools.s: src/simInterfaceTools.cpp.s
.PHONY : src/simInterfaceTools.s

# target to generate assembly for a file
src/simInterfaceTools.cpp.s:
	$(MAKE) -f CMakeFiles/SpeckleDestruction.dir/build.make CMakeFiles/SpeckleDestruction.dir/src/simInterfaceTools.cpp.s
.PHONY : src/simInterfaceTools.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... PacketMasterSim"
	@echo "... SpeckleDestruction"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sim/PacketMasterSim.o"
	@echo "... sim/PacketMasterSim.i"
	@echo "... sim/PacketMasterSim.s"
	@echo "... src/ImageGrabber.o"
	@echo "... src/ImageGrabber.i"
	@echo "... src/ImageGrabber.s"
	@echo "... src/P3KCom.o"
	@echo "... src/P3KCom.i"
	@echo "... src/P3KCom.s"
	@echo "... src/Speckle.o"
	@echo "... src/Speckle.i"
	@echo "... src/Speckle.s"
	@echo "... src/SpeckleDestruction.o"
	@echo "... src/SpeckleDestruction.i"
	@echo "... src/SpeckleDestruction.s"
	@echo "... src/SpeckleNuller.o"
	@echo "... src/SpeckleNuller.i"
	@echo "... src/SpeckleNuller.s"
	@echo "... src/dmTools.o"
	@echo "... src/dmTools.i"
	@echo "... src/dmTools.s"
	@echo "... src/simInterfaceTools.o"
	@echo "... src/simInterfaceTools.i"
	@echo "... src/simInterfaceTools.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

