//IMAGE PARAMS
#define IMXSIZE 80
#define IMYSIZE 125 
#define XCTRLSTART 40
#define XCTRLEND 79
#define YCTRLSTART 0
#define YCTRLEND 120
#define CENTERX 40
#define CENTERY 60
#define LAMBDAOVERD 2

//DM PARAMS
#define A 0
#define B 0
#define C 8

//NULLING PARAMS
#define MAXSPECKLES 16
#define SPECKLEWINDOW 8
#define EXCLUSIONZONE 8
#define NPHASES 4
